name: Code

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
          components: rustfmt, clippy

    - name : Cache Rust build  
    - uses: Swatinem/rust-cache@v2

    - name: Check formating
      run: cargo fmt -- --check
    
    - name: Clippy
      run: |
        cargo --version
        cargo clippy --version
        cargo clippy --all-targets --all-features -- --deny warnings

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
          components: rustfmt, clippy

    - name : Cache Rust build  
    - uses: Swatinem/rust-cache@v2

    - name: Check formating
      run: cargo fmt -- --check

    - name: Run tests
      run: cargo test --verbose

